apiVersion: batch/v1
kind: Job
metadata:
  name: print-datetime-job
spec:
  template:
    spec:
      containers:
        - name: print-datetime-container
          image: alpine
          command: ["sh", "-c", "echo The current date and time is: $(date)"]
      restartPolicy: Never
  backoffLimit: 0

